Fixing issue with solutions
StephaneGrabsia/uQuizz pull request #33
Opened 2023-02-11 18:06 UTC by StephaneGrabsia

This PR fix an issue that we noticed on the code submissions: when several exercises were present, the is_correct variable wasn't correct...

This was due to two main issues: 

- The request wasn't sending the right exercise number
- The back wasn't looking to the right solution when checking if it was correct

To test this PR you should : 

1. Launch the docker and go to localhost:8080
2. Create a teacher, a classroom, two exercises and a student
3. Connect yourself to the student main page, and try to answer the two exercises, and check if the results are corrects

2023-02-12 12:26 UTC, sachabinder submitted a review, later dismissed
Good job !

2023-02-13 22:12 UTC, SullivanENPC requested changes
Good job !

2023-02-13 22:13 UTC, SullivanENPC submitted a review, later dismissed
Good job !

2023-02-13 23:12 UTC, sachabinder approved these changes

2023-02-13 23:13 UTC, merged